- hosts: all

  tasks:

    - name: Upgrade All Packages
      yum: name=* state=latest
      sudo: true

    - name: Install random tools
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release
        - git
        - zsh
        - wget
        - vim
        - bzip2
        - net-tools
        - ntp
        - patch
      sudo: true

    - name: Set the timezone to Sydney and the correct time
      command: timedatectl set-timezone Australia/Sydney
      command: chkconfig ntpd on
      command: ntpdate time.apple.com
      sudo: true

    - name: configuring git
      script: config_scripts/git-config.sh

    - name: Install npm and node via EPEL yum repo
      yum: name=npm enablerepo=epel state=present
      sudo: true

    - name: Download Golang 1.5 (not in yum yet)
      get_url: url=https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz dest=/vagrant/go1.5.3linux-amd64.tar.gz

    - name: Install Golang
      command: tar -C /usr/local -xzf /vagrant/go1.5.3linux-amd64.tar.gz
      sudo: true

    - name: Download Ruby Install
      get_url: url=https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz dest=/vagrant/ruby-install-0.5.0.tar.gz

    - name: Extract Ruby Install
      command: tar -xzvf /vagrant/ruby-install-0.5.0.tar.gz
      sudo: true

    - name: Install Ruby Install
      sudo: true
      shell: cd ruby-install-0.5.0/ && make install

    - name: Download Chruby
      get_url: url=https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz dest=/vagrant/chruby-0.3.9.tar.gz

    - name: Extract Chruby
      command: tar -C /usr/local -xzvf /vagrant/chruby-0.3.9.tar.gz
      sudo: true

    - name: Install Chruby
      sudo: true
      shell: cd /usr/local/chruby-0.3.9 && make install

    - name: Install ruby 2.2.2
      shell: /usr/local/bin/ruby-install ruby 2.2.2

    - name: post install script
      script: post_install.sh
      sudo: true
