- hosts: all

  tasks:
    - name: Upgrade All Packages
      become: yes
      yum: name=* state=latest

    - name: Install random tools
      become: yes
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release
        - git
        - zsh
        - wget
        - vim
        - bzip2
        - net-tools
        - ntp
        - patch

    - name: Set the timezone to Sydney
      become: yes
      command: "{{ item }}"
      with_items:
          - timedatectl set-timezone Australia/Sydney
          - chkconfig ntpd on
          - ntpdate time.apple.com

    - name: configuring git
      script: config-scripts/git-config.sh

    - name: Install npm and node via EPEL yum repo
      become: yes
      yum: name=npm enablerepo=epel state=present

    - name: Install Golang 1.6.2 (not in yum)
      become: yes
      unarchive: src=https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz dest=/usr/local copy=no

    - name: Download Ruby Install
      become: yes
      unarchive: src=https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz dest=/opt copy=no

    - name: Install Ruby Install
      become: yes
      command: "chdir=/opt/ruby-install-0.5.0/ make install"

    - name: Download Install Chruby
      become: yes
      unarchive: src=https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz dest=/opt copy=no

    - name: Install Chruby
      become: yes
      command: "chdir=/opt/chruby-0.3.9 make install"

    - name: Install ruby 2.2.2
      shell: /usr/local/bin/ruby-install ruby 2.2.2

    - name: Install Docker and Docker Compose
      become: yes
      script: install-scripts/install-docker.sh

    - name: Post install script
      become: yes
      script: config-scripts/post-install.sh
